<h1> Demux-EM </h1>
<br>
Simple visual implementation

In [6]:
import h5py
import numpy as np
import pandas as pd
import pegasusio as io
from demuxEM.tools import *

<h3> Get HTO Counts Matrix and UMI Matrix </h3>
Both matrices come from .rds objects and were transformed into .csv and hdf5 during the pre processing step

In [2]:
hto_mat = pd.read_csv("/Users/mylenemarianagonzalesandre/Development/Bachelor-Thesis/demultiplex-pipeline/data/hto_matrix.csv")

In [3]:
hto_mat.head()

,Unnamed: 0,AGGCCACAGCGTCTAT,ATTGGTGAGTTCGCAT,GTGCAGCTCAGTCCCT,TAGTTGGGTCATACTG,TTCTTAGAGAAGGCCT,TAGACCAGTGTAACGG,TGACTAGTCAGTACGT,AGGGATGTCCAAAGTC,TGTCCCAGTCTCCACT,...,AGCGTCGAGACGCACA,GTCGGGTAGAGATGAG,AGCGTCGAGACTTTCG,TGGACGCGTCGACTAT,AGCGTCGGTTCAGGCC,AGCGTCGAGTGGGATC,AACACGTGTAGCCTCG,AGCGTCGAGGGCTTCC,GTCGGGTAGCATGGCA,AGCGTCGGTCCAGTAT
0,HTO_A,3,19,3,6,7,2,22,0,8,...,2,0,1,0,1,0,62,0,0,1
1,HTO_B,0,17,13,17,31,10,5,13,4,...,0,0,1,0,0,1,10,2,0,0
2,HTO_C,1,110,48,9,26,7,29,12,12,...,0,1,0,49,0,0,1,23,0,1
3,HTO_D,10,50,8,33,1769,17,17,4760,38,...,0,2,0,3,1,1,6,0,0,1
4,HTO_E,10,53,0,22,11,5418,2,18,28,...,0,0,1,1,0,0,9,0,28,21

In [4]:
filename = "/Users/mylenemarianagonzalesandre/Development/Bachelor-Thesis/demultiplex-pipeline/data/umi_matrix.h5"

with h5py.File(filename, "r") as f:
    # List all groups
    print("Keys: %s" % f.keys())
    a_group_key = list(f.keys())[0]

    # Get the data
    data = list(f[a_group_key])

Keys: <KeysViewHDF5 ['conversion?']>

In [5]:
pegasus.demultiplex(rna_data, hto_mat, min_signal=10.0, alpha=0.0, alpha_noise=1.0, tol=1e-06, n_threads=1)

'/Users/mylenemarianagonzalesandre/Development/Bachelor-Thesis/demultiplex-pipeline/data/umi_matrix.h5'